# Created by trellis-cli v1.0.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  customers.clearcomkeys.build:
    site_hosts:
    - canonical: customers.clearcomkeys.build
      redirects: []
    local_path: ../site
    branch: master
    repo: git@github.com:minemindmedia/clearcomkeys.com-clients-crm-roots-stack.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
